version: '3'

services:
  traefik:
    image: traefik:v2.8
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      #- ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      #- ./log:/log
      - /var/run/docker.sock:/var/run/docker.sock