version: '3'

services:
  traefik:
    image: traefik:v2.8
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# 本容器监听了 80 与 8080 端口，可在 http://127.0.0.1:8080/dashboard/#/ 查看