version: "3"
services:
  index:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "9000:80"
  api:
    image: nginx:alpine
    ports:
      - "9001:80"
    volumes:
      - ./server/api.conf:/etc/nginx/conf.d/default.conf
      - ./server:/usr/share/nginx/html