version: "3"
services:
  index:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./index.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  api:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./api.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html