version: "3"
services:
  index:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./client/index.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
  api:
    image: nginx:alpine
    ports:
      - "9001:80"
    volumes:
      - ./server/api.conf:/etc/nginx/conf.d/default.conf
      - ./server:/usr/share/nginx/html