// 将Religo浏览器插件中的本页单词添加到不背单词的生词本

// 一、收集本页所有生词（需要展示出本页生词）
let arr = []
document.querySelectorAll('.word-cards .name').forEach((node) => {
  arr.push(node.innerText.split('\n'))
})
JSON.stringify(arr)

const pick = [
  ['above', '以上'],
  ['alert', '警报'],
  ['among', '之间'],
  ['attribute', '属性'],
  ['basic', '基本'],
  ['basis', '基础'],
  ['brace', '括号'],
  ['branch', '分公司'],
  ['both', '都'],
  ['avatar', '阿凡达'],
  ['community', '社区'],
  ['combine', '结合'],
  ['check', '检查'],
  ['case', '案例'],
  ['concept', '概念'],
  ['condition', '条件'],
  ['contributor', '撰稿人'],
  ['counter', '计数器'],
  ['depend', '依赖'],
  ['describe', '描述'],
]

arr = [
  ['acknowledgement', '确认'],
  ['affect', '影响'],
  ['appearance', '外观'],
  ['approach', '方法'],
  ['cabbage', '卷心菜'],
  ['capital', '资本'],
  ['compact', '紧凑'],
  ['complex', '复杂'],
  ['concatenation', '串联'],
  ['conditional', '条件'],
  ['conditionally', '条件'],
  ['conduct', '进行'],
  ['consult', '咨询'],
  ['contain', '包含'],
  ['convenience', '方便'],
  ['convention', '公约'],
  ['converter', '转炉'],
  ['count', '计数'],
  ['curly', '卷曲'],
  ['current', '当前'],
  ['declare', '申报'],
  ['documentation', '文档'],
  ['either', '要么'],
  ['embed', '嵌入'],
  ['empty', '空'],
  ['entire', '整个'],
  ['escape', '逃脱'],
  ['exist', '存在'],
  ['export', '出口'],
  ['express', '表达'],
  ['expression', '表达'],
  ['extract', '提取物'],
  ['familiar', '熟悉'],
  ['feature', '特征'],
  ['finally', '最后'],
  ['find', '找到'],
  ['fire', '火'],
  ['framework', '框架'],
  ['garlic', '大蒜'],
  ['happen', '发生'],
  ['hatch', '舱口'],
  ['height', '高度'],
  ['hook', '钩'],
  ['however', '然而'],
  ['identify', '识别'],
  ['import', '进口'],
  ['include', '包括'],
  ['increment', '增量'],
  ['independent', '独立'],
  ['individual', '个人'],
  ['information', '信息'],
  ['insert', '插入'],
  ['installation', '安装'],
  ['instead', '相反'],
  ['introduction', '介绍'],
  ['late', '晚'],
  ['lift', '电梯'],
  ['link', '链接'],
  ['local', '当地'],
  ['logic', '逻辑'],
  ['logical', '逻辑'],
  ['loop', '环'],
  ['lot', '很多'],
  ['lowercase', '小写'],
  ['magenta', '品红'],
  ['manage', '管理'],
  ['meet', '满足'],
  ['more', '更多'],
  ['multiple', '多种'],
  ['nest', '巢'],
  ['notice', '通知'],
  ['object', '对象'],
  ['operator', '算子'],
  ['optional', '任选'],
  ['piece', '一块'],
  ['practice', '实践'],
  ['prefer', '宁愿'],
  ['prescribe', '订明'],
  ['previous', '以前'],
  ['previously', '先前'],
  ['privacy', '隐私'],
  ['product', '产品'],
  ['profile', '配置文件'],
  ['project', '项目'],
  ['prop', '道具'],
  ['provide', '提供'],
  ['quote', '报价'],
  ['radius', '半径'],
  ['recommend', '推荐'],
  ['reference', '参考'],
  ['regular', '定期'],
  ['rely', '依赖'],
  ['remember', '记得'],
  ['respond', '回应'],
  ['restrictive', '限制性'],
  ['result', '结果'],
  ['rule', '规则'],
  ['screen', '屏幕'],
  ['separate', '单独'],
  ['separately', '分别'],
  ['sibling', '同级'],
  ['simple', '简单'],
  ['special', '特殊'],
  ['specify', '指定'],
  ['statement', '语句'],
  ['strict', '严格'],
  ['such', '这样'],
  ['support', '支持'],
  ['survey', '调查'],
  ['syntax', '语法'],
  ['take', '采取'],
  ['technique', '技术'],
  ['term', '术语'],
  ['title', '标题'],
  ['toe', '脚趾'],
  ['together', '一起'],
  ['transform', '变换'],
  ['tutorial', '教程'],
  ['unfamiliar', '陌生'],
  ['uniquely', '独特'],
  ['unlike', '与'],
  ['upwards', '向上'],
  ['variable', '变量'],
  ['when', '当'],
  ['which', '哪'],
  ['while', '而'],
  ['width', '宽度'],
  ['wrap', '包裹'],
  ['wrapper', '包装'],
  ['runs', 'diarrhea'],
]

// 二、https://bbdc.cn/newword
// 打开控制台执行
const currentCount = document.querySelectorAll('.wordlist-word').length
const wordList = pick.map((w) => w[0])
wordList.forEach(async (word) => {
  const newWordData = encodeURIComponent(
    JSON.stringify({
      word: word,
      course: '*',
      wordidx: '*',
      infoidx: '100',
      selection: '*',
      info: '',
      opcode: '1',
    }),
  )
  const result = await fetch(`https://bbdc.cn/api/user-new-word`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: `newwordlist=${newWordData}`,
  })
  const resultRes = await result.json()
  console.log(resultRes)
})
console.log(currentCount)

// 刷新页面计算本次增加了多少
const addedCount =
  document.querySelectorAll('.wordlist-word').length - currentCount
console.log('本次增加', addedCount)
