version: "3"
services:
  index:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT=oss-cn-hongkong.aliyuncs.com
    ports:
      - "9100:80"