name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      Greeting: uat
    steps:
      - run: echo "事件：${{ github.event_name }}"
      - run: echo "当前系统：${{ runner.os }}"
      - run: echo "${{ github.repository }} 仓库下的 ${{ github.ref }} 分支"
      - name: Check out repository code # ？这里应该只是一个标注吧
        uses: actions/checkout@v3 # ？github提供的自动拉取仓库代码到镜像的代码？
      - name: 
        run: |
          ls ${{ github.workspace }}
      - run: echo "本次job的状态 ${{ job.status }}"
      - run: echo $CI
      - run: echo $GITHUB_REF_NAME
      - run: echo $PASS_WORD
      - run: echo $USER_NAME
      - run: echo $HOME

