name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "事件：${{ github.event_name }}"
      - run: echo "当前系统：${{ runner.os }}"
      - run: echo "${{ github.repository }} 仓库下的 ${{ github.ref }} 分支"
      - name: Check out repository code # ？这里应该只是一个标注吧
        uses: actions/checkout@v3 # ？github提供的自动拉取仓库代码到镜像的代码？
      - name: 列出当前存储库中的文件
        run: |
          ls ${{ github.workspace }}
      - run: 本次job的状态：${{ job.status }}"
      - run: echo "是否在CI中：$CI"
      - run: echo "当前分支：$GITHUB_REF_NAME"
      - run: echo "这个环境变量是在github配置中设置的：$PASS_WORD"
      - run: echo "这个环境变量是在项目根目录的.env中读取的：$USER_NAME"
      - run: echo "尝试读取linux中的环境变量：$HOME"

